### ISSUE TITLE
IzPacked installer does not install my application.

### ISSUE THREAD

**Issue by markehammons** [bmc/sbt-izpack#1]
I had izpack set up for maven, and I had an izpack installer easily created by it. My install.xml is below.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<installation version="1.0">
    <info>
        <appname>OpenMOLE</appname>
        <appversion>$VERSION$</appversion>
        <uninstaller write="yes" />
        <javaversion>1.7</javaversion>
        <pack200 />
    </info>

    <packs>
        <pack name="OpenMOLE Core" required="yes">
        <description>"OpenMOLE Core</description>
            <fileset dir="../openmole/" targetdir="$INSTALL_PATH" />
            <file src="register.bat" targetdir="$INSTALL_PATH" override="true" />
    </pack>
        <pack name="OpenMOLE Runtime" required="yes">
        <description>"OpenMOLE Runtime</description>
            <file src="../dependency/org.openmole.runtime.tar.gz" targetdir="$USER_HOME/.openmole/runtime/" />
            <file src="../jvm-linux-x64.tar.gz" targetdir="$USER_HOME/.openmole/runtime/" />
            <file src="../jvm-linux-i386.tar.gz" targetdir="$USER_HOME/.openmole/runtime/" />
    </pack>
        <pack name="OpenMOLE Icons" required="yes">
        <description>"OpenMOLE Icons</description>
            <file src="./openmole.ico" targetdir="$INSTALL_PATH/" />
            <file src="./openmole-uninstall.ico" targetdir="$INSTALL_PATH/" />
            <file src="./openmole.png" targetdir="$INSTALL_PATH/" />
            <file src="./openmole-uninstall.png" targetdir="$INSTALL_PATH/" />
        <executable targetfile="$INSTALL_PATH/openmole" stage="never" />
        </pack>

    </packs>

    <resources>
        <res id="LicencePanel.licence" src="AGPLv3.txt"/>
        <res id="shortcutSpec.xml" src="shortcutSpec.xml" /> 
        <res id="Unix_shortcutSpec.xml" src="Unix_shortcutSpec.xml" /> 
    <!--<res id="ProcessPanel.Spec.xml" src="processPanelSpec.xml" />-->
    </resources>

    <panels>
        <panel classname="HelloPanel" />
        <panel classname="LicencePanel"/>
        <panel classname="TargetPanel" />
        <panel classname="InstallPanel" />
        <panel classname="ShortcutPanel"/>
    <!--<panel classname="ProcessPanel" />-->
        <panel classname="SimpleFinishPanel" />
    </panels>

    <locale>
        <langpack iso3="eng"/>
    </locale>

    <guiprefs resizable="yes" width="640" height="480" />

    <native type="izpack" name="ShellLink.dll" />

</installation>
```

I converted it to the install.yml below.

``` yaml
info:
    appName: OpenMOLE
    appVersion: $version
    createUninstaller: yes
    javaVersion: 1.7
    runPrivileged:
        enabled: no
    pack200: yes

packs:
    pack:
        name: OpenMOLE Core
        required: yes
        description: OpenMOLE Core
        fileset:
            includes: $installSourceDir/openmole/
            targetDir: $INSTALL_PATH
        file:
            src: $installSourceDir/resources/register.bat
            targetDir: $INSTALL_PATH/register.bat
            override: true
    pack:
        name: OpenMOLE Runtime
        required: yes
        description: OpenMOLE Runtime
        file:
            src: $installSourceDir/runtime/runtime.tar.gz
            targetDir: $USER_HOME/.openmole/runtime/
        file:
            src: $installSourceDir/runtime/jvm-x64.tar.gz
            targetDir: $USER_HOME/.openmole/runtime/
        file:
            src: $installSourceDir/runtime/jvm-386.tar.gz
            targetDir: $USER_HOME/.openmole/runtime/
    pack:
        name: OpenMOLE Icons
        required: yes
        description: OpenMOLE Icons
        file:
            src: $installSourceDir/resources/openmole.ico
            targetDir: $INSTALL_PATH/openmole.ico
            override: true
        file:
            src: $installSourceDir/resources/openmole-uninstall.ico
            targetDir: $INSTALL_PATH/openmole-uninstall.ico
            override: true
        file:
            src: $installSourceDir/resources/openmole.png
            targetDir: $INSTALL_PATH/openmole.png
            override: true
        file:
            src: $installSourceDir/resources/openmole-uninstall.png
            targetDir: $INSTALL_PATH/openmole-uninstall.png
            override: true
        executable:
            targetFile: $INSTALL_PATH/openmole
            stage: never

resources:
    resource:
        id: LicencePanel.licence
        src: $installSourceDir/resources/AGPLv3.txt
    resource:
        id: shortcutSpec.xml
        src: $installSourceDir/resources/shortcutSpec.xml
    resource:
        id: Unix_shortcutSpec.xml
        src: $installSourceDir/resources/Unix_shortcutSpec.xml

panels:
    panel:
        className: HelloPanel
    panel:
        className: LicencePanel
    panel:
        className: TargetPanel
    panel:
        className: InstallPanel
    panel:
        className: ShortcutPanel
    panel:
        className: SimpleFinishPanel

languages:
    - eng

guiprefs:
    resizable: yes
    width: 640
    height: 480
```

There are two problems with this. First, I cannot figure out how to add the custom XML for my native element in the xml. Second, sbt-izpack parses this yml and my settings just fine, and produces a 156MB installer.jar, but when I run that jar it only unpacks the uninstaller jar. Nothing else is put in the targetDirs. What is going on? Does my yaml have a bug in it?
