### ISSUE TITLE
Exclude rule that begins with /** takes very long

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [bmc/sbt-izpack#13]
If I write this, it takes too long:

```
fileset:
  includes: $dirWebapp/**
  excludes: /**/*.py
  targetDir: $INSTALL_PATH/webIma
```

I have to write this redundant style instead:

```
fileset:
  includes: $dirWebapp/**
  excludes: $dirWebapp/**/*.py
  targetDir: $INSTALL_PATH/webIma
```

What is worst, in the 2nd case, no exclude rule is generated in the generated `izpack.xml`.  It is also quite verbose, listing all the subdirectories.

**Comment by DavidPerezIngeniero** [comment]
My 2nd try:

```
fileset:
  includes: $dirWebapp/**
  regexExcludes: .*\.py
  targetDir: $INSTALL_PATH/webIma
```

I don't see any exclusion either in the generated `izpack.xml`.  :-(

I think it would have been better, to stick closely to the IzPack spec, as it is more powerful, and easier to implement.
