### ISSUE TITLE
excludes in a fileset cannot start with *

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [bmc/sbt-izpack#9]
Also, I cannot specify an excludes like this:

    fileset:
        targetDir: $INSTALL_PATH
        includes: myDir/**
        excludes: **/*.py

Why not?

**Comment by bmc** [comment]
Please post the error you get. It'll help. I can reproduce it, but if you already have the stack trace, it saves me time.

**Comment by bmc** [comment]
This is a documentation issue. I'll update the docs. The problem is that a naked "*" confuses the YAML parser. Use this:

```yaml
fileset:
  targetDir: $INSTALL_PATH
  includes: myDir/**
  excludes: "**/*.py"
```
